
CONFIG_BT_LL_SW_LLCP_LEGACY=y

CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Debounce (helps with key chatter / double-presses)
# If still chattering, try 25 or 30ms
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15
