manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ojfw20
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 9c317f7a83ab1856fac5e5677cdd18449409eb08
      repo-path: zmkTrackballFork
      import: app/west.yml
  self:
    path: config
